import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { AboutComponent } from './about/about.component';
import { DemosComponent } from './demos/demos.component';
import { BlogListComponent } from './blog/blog-list.component';
import { BlogDetailComponent } from './blog/blog-detail.component';
import { IFAQComponent } from './ifaq/ifaq.component';
import { CareersComponent } from './careers/careers.component';
import { CareersDetailComponent } from './careers/careers-detail.component';
import { TeamComponent } from './team/team.component';
import { NewsComponent } from './news/news.component';
import { NewsDetailComponent } from './news/news-detail.component';
import { NewsDac2026Component } from './news/news-dac2026.component';
import { NewsBitMesraAwardComponent } from './news/news-bit-mesra-award.component';
import { NewsNeevsemiPartnershipComponent } from './news/news-neevsemi-partnership.component';
import { StartupProgramComponent } from './startup-program/startup-program.component';

export const routes: Routes = [
  { path: '',                component: HomeComponent },
  { path: 'about',           component: AboutComponent },
  { path: 'team',            component: TeamComponent },
  { path: 'demos',           component: DemosComponent },
  { path: 'news',            component: NewsComponent },
  { path: 'news/2026-08-release-neevsemi-partnership', component: NewsNeevsemiPartnershipComponent },
  { path: 'news/dac-2026',   component: NewsDac2026Component },
  { path: 'news/technical-advisors', component: NewsDetailComponent },
  { path: 'news/bit-mesra-award', component: NewsBitMesraAwardComponent },
  { path: 'startup-program', component: StartupProgramComponent },
  { path: 'blogs',           component: BlogListComponent },
  { path: 'blogs/:slug',     component: BlogDetailComponent },
  { path: 'ifaq',            component: IFAQComponent },
  { path: 'careers',         component: CareersComponent },
  { path: 'careers/:slug',   component: CareersDetailComponent },
  { path: '**',              redirectTo: '' },
];
